import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { FeatureFlagProvider } from './_components/FeatureFlagContext';
import { getFlags } from "@/services";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const flags = getFlags();

  return (
    <html lang="en">
      <body className={inter.className}>
        <FeatureFlagProvider flags={flags}>{children}</FeatureFlagProvider></body>
    </html>
  );
}
